server:
  port: 8082

spring:
  application:
    name: app
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sys
    username: root
    password: mysql
  messages:
    basename: i18n/messages
  rabbitmq:
    enabled: ${RABBIT_ENABLED:true}
    listener:
      simple:
        default-requeue-rejected: false
    template:
      reply-timeout: ${RABBIT_REPLY_TIMEOUT:15000}
